"""Generate expanded dataset and write data/abstracts.csv"""
import os, csv, random
os.makedirs("data", exist_ok=True)

random.seed(42)

AI_ML = [
    "We propose a novel deep reinforcement learning framework for autonomous agents combining policy gradient methods with model-based planning. Our approach achieves state-of-the-art performance on the MuJoCo benchmark suite.",
    "This paper introduces a transformer-based language model pre-trained on 1.5 trillion tokens. Fine-tuning experiments demonstrate significant improvements on GLUE and SuperGLUE benchmarks.",
    "We present a meta-learning algorithm enabling few-shot adaptation across diverse task distributions. The proposed MAML variant converges faster and generalises better than prior approaches.",
    "A novel generative adversarial network architecture is proposed for high-fidelity image synthesis using spectral normalisation and adaptive instance normalisation.",
    "We introduce a self-supervised contrastive learning framework that learns robust visual representations without labelled data, outperforming supervised baselines on linear evaluation protocols.",
    "This work explores neural architecture search using evolutionary algorithms combined with gradient-based optimisation, discovering architectures matching human-designed networks at lower cost.",
    "We propose a federated learning scheme with differential privacy guarantees for training ML models on distributed data without sharing raw samples.",
    "A knowledge distillation technique transfers dark knowledge from ensemble teachers to a compact student network, achieving 5× compression with less than 1 percent accuracy drop.",
    "We study the optimisation landscape of deep neural networks and prove spurious local minima are exponentially rare under mild assumptions on data distribution and network width.",
    "This paper proposes a linear-complexity attention mechanism enabling transformers to handle documents of 100,000 tokens without approximation.",
    "Bayesian deep learning with uncertainty quantification is applied to medical diagnosis, providing calibrated confidence scores to support clinical decision-making.",
    "We introduce a continual learning algorithm that mitigates catastrophic forgetting via elastic weight consolidation extended with a generative replay buffer.",
    "Graph neural networks are extended with hyperbolic geometry to better capture hierarchical relationships in citation networks and biological interaction graphs.",
    "We propose a causal inference framework integrated with deep learning to disentangle spurious correlations from true causal relationships in observational datasets.",
    "A new optimiser combining adaptive learning rates with momentum correction demonstrates faster convergence than Adam across classification and language benchmarks.",
    "We present a hierarchical variational autoencoder that learns disentangled latent representations of structured data, enabling controllable generation and interpolation.",
    "A neural machine translation model is enhanced with cross-lingual pre-training on 100 languages, achieving zero-shot transfer on low-resource language pairs.",
    "We study reward shaping in sparse-reward reinforcement learning and propose an automated curriculum that progressively increases task difficulty based on agent competence.",
    "Mixture-of-experts language models are scaled to one trillion parameters using a learned routing mechanism that achieves balanced expert utilisation across diverse inputs.",
    "We introduce a probabilistic programming language with automatic differentiation support, enabling variational inference in complex hierarchical Bayesian models.",
    "Active learning is combined with Gaussian process regression to minimise labelling effort in molecular property prediction, reducing annotation cost by 60 percent.",
    "We propose a self-play training protocol for dialogue agents that improves negotiation strategy without human interaction data.",
    "A neural theorem prover is trained on formal mathematical proofs and learns to generate novel proof steps for undergraduate-level algebra problems.",
    "We present an energy-based model for few-shot image generation that scores samples using a learned compatibility function between images and class prototypes.",
    "Prompt engineering strategies are systematically benchmarked across seven large language models, revealing that chain-of-thought prompting consistently improves arithmetic reasoning.",
    "We introduce a multimodal foundation model pre-trained on text, images, and audio that achieves competitive performance on each modality without task-specific fine-tuning.",
    "A recurrent neural network is trained on protein sequence data to predict secondary structure, achieving state-of-the-art results on CASP benchmarks.",
    "We study neural scaling laws for language models and derive a compute-optimal training recipe that maximises performance under a fixed computational budget.",
    "A differentiable physics engine is embedded within a deep learning pipeline for model-based robot manipulation planning without human-engineered dynamics models.",
    "We propose a sparse attention transformer that routes tokens to specialised heads based on content, reducing perplexity on long-document language modelling tasks.",
]

COMPUTER_VISION = [
    "We propose a real-time object detection network using depthwise separable convolutions and feature pyramid networks running at 120 FPS on embedded hardware.",
    "A 3D point cloud segmentation method based on PointNet++ with hierarchical feature aggregation achieves state-of-the-art results on ScanNet and ShapeNet.",
    "This paper presents a vision transformer architecture for semantic segmentation enriched with spatial positional encodings learned via sinusoidal functions.",
    "We introduce a contrastive self-supervised method for medical image analysis leveraging augmentation policies tailored to radiology images.",
    "A neural implicit surface representation is proposed for 3D reconstruction from multi-view stereo images, outperforming explicit mesh-based methods.",
    "We propose a novel optical flow estimation network using deformable convolutions and cost volume aggregation, achieving leading results on KITTI and Sintel.",
    "This work addresses video understanding by combining temporal attention with 2D spatial convolutions for action recognition in long video clips.",
    "We present a face super-resolution network using channel attention and residual dense blocks to recover fine facial details from 4× downsampled inputs.",
    "A domain adaptation framework for autonomous driving perception uses adversarial training to bridge the sim-to-real gap in object detection.",
    "We introduce a medical image registration algorithm based on diffeomorphic deformations parameterised by a convolutional neural network.",
    "Instance segmentation is improved via a mask transformer that attends to object queries in parallel, eliminating sequential RNN-based approaches.",
    "A diffusion model is applied to image inpainting, generating coherent textures conditioned on surrounding context and semantic labels.",
    "We propose a zero-shot object detection method by aligning visual region features with textual descriptions from a large language model.",
    "Depth estimation from a single RGB image is improved by incorporating surface normal constraints and uncertainty-aware training losses.",
    "Event camera data is processed with a spiking neural network for high-speed motion estimation, reducing latency to under 1 ms.",
    "We present a scene graph generation model that jointly predicts objects and their pairwise visual relationships in a single forward pass.",
    "A panoptic segmentation architecture unifies semantic and instance segmentation under a shared pixel-wise prediction head trained end-to-end.",
    "We propose a neural radiance field variant that achieves real-time rendering of dynamic scenes by factorising appearance and motion.",
    "Stereo matching accuracy is improved using a recurrent cost volume filtering network that propagates confidence estimates across disparity levels.",
    "We introduce a few-shot image classification model that adapts to new visual categories from five examples using a learned nearest-centroid classifier.",
    "A lane detection network for autonomous driving uses polynomial curve fitting combined with a transformer decoder to predict structured lane representations.",
    "We present a crowd counting model using multi-scale dilated convolutions and density map regression, achieving state-of-the-art results on ShanghaiTech.",
    "A human pose estimation framework predicts 3D joint positions from monocular video using a temporal graph convolutional network.",
    "We introduce a universal image restoration network that handles denoising, deblurring, and super-resolution with a single set of shared weights.",
    "Aerial image segmentation is improved with a context aggregation module that captures both local texture and global spatial layout information.",
    "We propose a cross-modal image retrieval system aligning visual features with natural language queries via a shared embedding space.",
    "A generative model for 3D shape completion takes partial point clouds as input and predicts missing regions using a variational decoder.",
    "We present a video object segmentation method that propagates segmentation masks across frames using learned optical flow and memory attention.",
    "Licence plate recognition in adverse weather conditions is improved using domain randomisation during training and a deblurring pre-processing module.",
    "We introduce a retinal disease screening system combining fundus image classification with saliency map generation to highlight diagnostic regions.",
]

DATA_SCIENCE = [
    "We develop a predictive model for customer churn in telecommunications using gradient-boosted trees and SHAP-based feature importance, achieving 91 percent AUC.",
    "This paper proposes a time-series anomaly detection method combining LSTM autoencoders with statistical process control charts for industrial IoT sensors.",
    "A data pipeline architecture for real-time ETL processing of social media streams is presented using Apache Kafka and Spark Structured Streaming at petabyte scale.",
    "We introduce a causal impact estimation technique for A/B testing that corrects for network effects and user interference in large-scale online experiments.",
    "Survival analysis models are applied to predict equipment failure integrating sensor data with maintenance logs via a Cox proportional hazards model.",
    "We propose a recommendation system that combines collaborative filtering with graph-based propagation to capture higher-order user-item relationships.",
    "This work presents a framework for automated feature engineering using genetic programming, discovering non-linear interaction features that improve predictions.",
    "A probabilistic forecasting method outputs full predictive distributions for energy demand, enabling better power grid management under uncertainty.",
    "We study data leakage patterns in public ML benchmarks and propose a pipeline audit framework that detects temporal and identifier-based leakage.",
    "A multi-task learning approach to fraud detection jointly optimises transaction classification and merchant risk scoring at low false positive rates.",
    "We present an explainability framework for black-box tabular models using prototype examples and counterfactual explanations aligned with domain constraints.",
    "Natural language processing is applied to unstructured electronic health records for clinical concept extraction, achieving 89 percent F1 on medication mentions.",
    "We introduce a clustering algorithm for high-dimensional genomics data leveraging sparse subspace assumptions to robustly identify cancer subtypes.",
    "A missing data imputation method based on variational autoencoders outperforms MICE on health survey datasets with over 40 percent missingness.",
    "We build a social network analysis pipeline to detect coordinated inauthentic behaviour on Twitter using graph motif patterns and temporal activity bursts.",
    "A streaming data architecture for real-time sports analytics is presented, ingesting event telemetry and producing in-game win probability estimates with sub-second latency.",
    "We propose a hierarchical Bayesian model for multi-level marketing attribution that accounts for cross-channel spillover and temporal decay.",
    "Demand forecasting for retail is improved using external data sources including weather, events, and social sentiment fused via a multi-modal ensemble.",
    "We introduce a graph-based supply chain risk model that propagates disruption probabilities through supplier networks to assess second-tier exposure.",
    "A semi-supervised learning framework is applied to document classification in legal discovery, reducing manual review effort by 73 percent.",
    "We present a real-time credit scoring pipeline that processes streaming transaction events and retrains daily using an online gradient boosting algorithm.",
    "Clickstream data from e-commerce users is modelled as a Markov chain to predict purchase intent and trigger personalised interventions.",
    "We propose a bootstrap aggregation strategy for spatial interpolation of air quality sensor data across urban areas with sparse monitoring coverage.",
    "An automated machine learning toolkit is evaluated on 100 OpenML datasets, demonstrating competitive accuracy against hand-crafted pipelines within 10 minutes.",
    "We study Simpson's paradox in observational health data and propose a stratified analysis workflow that prevents misleading conclusions from aggregated statistics.",
    "A transfer learning approach adapts pre-trained tabular models from financial services to insurance risk scoring with minimal labelled data.",
    "We present a real-options framework for data centre capacity planning that models demand uncertainty using Monte Carlo simulation and dynamic programming.",
    "Topic modelling with latent Dirichlet allocation is applied to customer support tickets to surface recurring pain points and prioritise product improvements.",
    "We introduce a privacy-preserving analytics framework using local differential privacy that enables population-level statistics without collecting individual records.",
    "A dashboard system for hospital operational intelligence aggregates 15 data sources in real time, reducing ICU bed management decision latency by 40 percent.",
]

CYBERSECURITY = [
    "We present a deep learning-based intrusion detection system for IoT networks that identifies zero-day attacks by modelling normal traffic with a variational autoencoder.",
    "A transformer model fine-tuned on malware assembly code classifies malware families with 97 percent accuracy, outperforming signature-based antivirus tools.",
    "This paper proposes a fuzzing framework guided by reinforcement learning that generates adversarial inputs to discover vulnerabilities in binary programs.",
    "We introduce a federated anomaly detection protocol for industrial control systems that preserves confidentiality while detecting coordinated multi-site attacks.",
    "A graph-based approach models network lateral movement patterns to detect advanced persistent threats before data exfiltration occurs.",
    "We study adversarial machine learning attacks on autonomous vehicle perception and propose certified defences using randomised smoothing.",
    "A privacy-preserving authentication protocol using zero-knowledge proofs is designed for mobile edge computing with constrained devices.",
    "We propose a honeypot orchestration system powered by reinforcement learning that dynamically adapts deception strategies based on attacker behaviour.",
    "Phishing URL detection is improved using a character-level convolutional neural network trained on URL syntax features without accessing page content.",
    "We present a vulnerability prediction model trained on code commits and bug reports, prioritising security patches in large open-source codebases.",
    "A side-channel attack on deep learning accelerators recovers model weights through power trace analysis, demonstrating intellectual property risks.",
    "We introduce a secure multi-party computation protocol for collaborative threat intelligence sharing that prevents information leakage between organisations.",
    "Ransomware behaviour is modelled as a sequence of file system events and classified with a stacked LSTM achieving 99.2 percent detection accuracy.",
    "We design a post-quantum key encapsulation mechanism based on lattice problems suitable for constrained IoT hardware with 2 KB RAM.",
    "A blockchain-based audit trail system ensures tamper-evidence and regulatory compliance for cloud data provenance without centralised trust.",
    "We present a network traffic analysis framework that fingerprints encrypted TLS flows using statistical flow features without decryption.",
    "A memory forensics tool reconstructs process injection artefacts from RAM dumps to attribute attacks to known threat actor toolkits.",
    "We introduce a hardware-assisted control flow integrity mechanism that detects ROP gadget chains at runtime with under 2 percent overhead.",
    "Domain generation algorithm detection is improved using a hybrid character-level and semantic model trained on passive DNS telemetry.",
    "We propose a moving target defence strategy for web applications that dynamically randomises API endpoints to disrupt automated scanning.",
    "A machine learning classifier distinguishes benign scripting from malicious PowerShell execution by modelling abstract syntax tree features.",
    "We present a deception-based active defence that plants synthetic credentials in enterprise directories to detect credential stuffing attacks.",
    "Binary similarity detection across compiler optimisation levels is achieved using a siamese neural network on lifted intermediate representation.",
    "We introduce a continuous authentication system for mobile devices using gait and touch behavioural biometrics to detect session hijacking.",
    "A static taint analysis framework for Android applications tracks personal data flows to identify privacy policy violations automatically.",
    "We propose a cyber threat hunting methodology using unsupervised clustering of endpoint telemetry to surface anomalous process behaviour.",
    "Firmware security is improved via automated patch extraction and binary diffing to identify vulnerability fixes in IoT device updates.",
    "We present a privacy risk quantification framework that scores re-identification risk in synthetic datasets using linkage attack simulation.",
    "A neural network model predicts exploit development timelines from vulnerability disclosure metadata, enabling prioritised patch deployment.",
    "We introduce a supply chain integrity verification protocol that detects tampered software artefacts using reproducible build attestations.",
]

SYSTEMS_SE = [
    "We propose a microservices orchestration framework that uses reinforcement learning to auto-scale containers based on predicted workloads, reducing cloud costs by 34 percent.",
    "A static analysis tool detects concurrency bugs in Rust programs by modelling ownership transfers and lifetime violations as constraint satisfaction.",
    "This paper introduces a just-in-time compilation strategy for dynamic languages that inlines polymorphic call sites based on runtime type feedback.",
    "We present a distributed consensus algorithm tolerant to Byzantine faults with O(log n) communication complexity for internet-scale coordination.",
    "A formal verification method based on model checking is applied to smart contracts on Ethereum, detecting reentrancy and integer overflow vulnerabilities.",
    "We introduce a serverless computing framework that minimises cold-start latency using predictive pre-warming based on access pattern forecasting.",
    "A compiler optimisation pass vectorises irregular data-parallel loops using polyhedral analysis, improving sparse matrix benchmark performance.",
    "We design a real-time operating system scheduler combining earliest-deadline-first with energy harvesting awareness for batteryless embedded systems.",
    "This work presents a program synthesis technique that infers loop invariants from input-output examples using enumerative search with constraint propagation.",
    "A software testing framework automatically generates regression test suites from production traffic logs, achieving 85 percent branch coverage.",
    "We propose a hardware-software co-design methodology for neural network inference accelerators that jointly optimises quantisation, pruning, and dataflow.",
    "A memory-safe systems programming language extension supports safe foreign function interfaces to C libraries via automated wrapper generation.",
    "We study tail latency in distributed databases under mixed workloads and propose a routing algorithm that reduces P99 latency by 60 percent.",
    "A log analysis pipeline uses transformer embeddings to cluster operational logs and surface root causes of production incidents in under 30 seconds.",
    "We present a CI/CD framework with built-in chaos engineering hooks that stress-tests microservice deployments before merging to production.",
    "A storage engine is proposed using learned index structures to replace B-trees, reducing range query latency by 45 percent on SSD hardware.",
    "We introduce a task scheduling algorithm for heterogeneous compute clusters that minimises makespan using a graph neural network to estimate job runtimes.",
    "A transactional memory system extends hardware TSX with software fallback to maintain serialisability under high contention workloads.",
    "We present a container image deduplication service that identifies shared layer content across registries, reducing storage costs by 52 percent.",
    "A protocol for zero-downtime database schema migrations is designed and evaluated across PostgreSQL and MySQL at 10 million rows per second.",
    "We propose a live migration technique for virtual machines that achieves sub-100 ms downtime by prefetching dirty memory pages during pre-copy.",
    "An automated performance regression detection system analyses continuous integration benchmark results using statistical change point detection.",
    "We introduce a library for software transactional memory in Rust that leverages the ownership type system to eliminate data races at compile time.",
    "A query optimiser for multi-tenant cloud databases uses reinforcement learning to select execution plans based on observed resource utilisation.",
    "We present a build system that achieves incremental compilation of large C++ codebases by tracking fine-grained header dependency graphs.",
    "A mesh networking protocol for IoT devices achieves reliable multi-hop routing under 30 percent packet loss using fountain codes and opportunistic forwarding.",
    "We introduce a smart contract upgradeability pattern that preserves storage layout compatibility across protocol upgrades without proxy contract overhead.",
    "A distributed tracing system correlates spans across polyglot microservices using baggage propagation and tail-based sampling to reduce overhead.",
    "We propose a file system design for non-volatile memory that exploits byte-addressability to reduce journaling overhead by 80 percent.",
    "An operating system kernel extension enables hardware-isolated enclaves for user-space applications without trusted execution environment hardware.",
]

rows = []
for text in AI_ML:       rows.append({"text": text, "label": "AI / Machine Learning"})
for text in COMPUTER_VISION: rows.append({"text": text, "label": "Computer Vision"})
for text in DATA_SCIENCE: rows.append({"text": text, "label": "Data Science / Analytics"})
for text in CYBERSECURITY: rows.append({"text": text, "label": "Cybersecurity"})
for text in SYSTEMS_SE:  rows.append({"text": text, "label": "Systems / Software Engineering"})

with open("data/abstracts.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["text", "label"])
    writer.writeheader()
    writer.writerows(rows)

print(f"Generated {len(rows)} samples → data/abstracts.csv")